# Generated by Django 5.1.7 on 2025-03-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tasks_user_id_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
    ]
